// <auto-generated />
using System;
using MAVN.Service.AdminManagement.MsSqlRepositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MAVN.Service.AdminManagement.MsSqlRepositories.Migrations
{
    [DbContext(typeof(AdminManagementContext))]
    [Migration("20200630082819_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("admin_users")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("MAVN.Service.AdminManagement.MsSqlRepositories.Entities.AdminUserEntity", b =>
                {
                    b.Property<string>("AdminUserId")
                        .HasColumnName("admin_id")
                        .HasColumnType("text");

                    b.Property<string>("EmailHash")
                        .IsRequired()
                        .HasColumnName("email_hash")
                        .HasColumnType("char(64)");

                    b.Property<bool>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("is_disabled")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnName("registered_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("UseCustomPermissions")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("use_custom_permissions")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("AdminUserId");

                    b.HasIndex("EmailHash")
                        .IsUnique();

                    b.ToTable("AdminUser");
                });

            modelBuilder.Entity("MAVN.Service.AdminManagement.MsSqlRepositories.Entities.EmailVerificationCodeEntity", b =>
                {
                    b.Property<string>("AdminId")
                        .HasColumnName("admin_id")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnName("expire_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsVerified")
                        .HasColumnName("is_verified")
                        .HasColumnType("boolean");

                    b.Property<string>("VerificationCode")
                        .IsRequired()
                        .HasColumnName("code")
                        .HasColumnType("text");

                    b.HasKey("AdminId");

                    b.HasIndex("VerificationCode")
                        .IsUnique();

                    b.ToTable("email_verification_codes");
                });

            modelBuilder.Entity("MAVN.Service.AdminManagement.MsSqlRepositories.Entities.PermissionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("id")
                        .HasColumnType("text");

                    b.Property<string>("AdminUserId")
                        .IsRequired()
                        .HasColumnName("admin_id")
                        .HasColumnType("text");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnName("level")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnName("type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AdminUserId");

                    b.ToTable("permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
